django4/src/blog/urls.py
from django.urls import path
from blog.views import *
app_name = 'blog'
urlpatterns =[
    #뷰 클래스를 url 등록시, 뷰클래스.as_view()함수로 등록함
    path('',Index.as_view(), name = 'index'),
    #DetailView를 상속받은 클래스뷰는 pk매개변수에 id변수값을 넘겨줘야함
    path('<int:pk>',Detail.as_view(), name = 'detail'),
    path('posting/', Posting.as_view(), name='posting'),
    path('search/', Postsearch.as_view(), name='postsearch')
    ]

django4/src/django4/urls.py
from django.contrib import admin
from django.urls import path, include
from bookmark.views import *

# 기본 도메인이 웹서버가 실행되는 환경에 맞춰짐
#개발 과정에서의 기본 도메인 주소: 127.0.0.1:8000/
'''
url.py: 만들어진 뷰함수/클래스를 url에 등록하는 공간
path (요청할url주소, 호출된 함수/클래스)
urlpatterns : 처리할수 있는 url 뷰를 저장하는 변수
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    #http://127.0.0.1:8000/ 입력 시, main 뷰함수가 호출됨
    path('', main),
    path('booklist/', booklist),
    #127.0.0.1:8000/숫자값/ 입력시 . getBook 뷰함수가 호출됨
    path('<int:book_id>/',getBook),
    #127.0.0.1:8000/vote/로 시작하는 모든 요청들을
    #vote폴더의 urls.py에서 관리하도록 등록하는 과정
    path('vote/',include('vote.urls')),
    path('login/',include('customlogin.urls')),
    #social_django 폴더의 urls.py를 등록
    #다른 개발자가 만든 어플리케이션의 urls.py를 등록하고 사용할때,
    #app_name 변수에 어떤값이 있는지 확인하지 않고 새로운 그룹명을 지정할 수 있음
    #-> include함수의 namespace 매개변수에 원하는 그룹명 지정
    path('social/',include('social_django.urls',namespace = 'social')),
    path('blog/',include('blog.urls'))
]

#사용자가 이미지, 첨부파일 요청 URL을 사용하면,
#서버의 하드디스크에 파일을 http로 넘겨줄 수 있도록 등록하는 작업

from django.conf import settings #settings.py 임포트
from django.conf.urls.static import static#URL과 폴더경로를 등록하는 함수

#path 함수대신 static함수를 사용함
#127.0.0.1:8000/files/로 시작하는 요청은 프로젝트폴더/files/에서 파일을 꺼내도록
#url 등록
urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

django4/src/vote/urls.py
'''
Created on 2019. 4. 21.

@author: 405-5
'''
'''
어플 별도의 url conf를 만들수있음
단, app name 와 urlpatterns 변수 정의해야함 (이름이 틀리면 url conf가 설정되지않음)
app_name: 이파일에 정의한 url들의 그룹이름(문자열)
urlpatterns: path함수를 이용해 뷰함수를 등록하는 변수 (리스트)
만들어진 urls.py를 프로잭트의 urls.py에 알려줘야함
'''
from django.urls import path
from vote.views import *
app_name='vote'
# 기본 도메인 주소 : 127.0.0.1:8000/vote/
#127.0.0.1:8000/vote/요청이 들어오면 index함수 호출

urlpatterns=[
    path('',index),
    #127.0.0.1:8000/vote/숫자값 요청이 들어오면 detail함수 호출
    #숫자값은 q_id 매개변수에 값으로 사용됨
    path('<int:q_id>/',detail),
    #127.0.0.1:8000/vote/vote/ -> vote함수 호출
    path('vote/',vote),
    #127.0.0.1:8000/vote/result/숫자값 -> result함수 호출
    path('result/<int:q_id>/',result),
    #파이썬코드나 html에서 vote:qr 별칭으로 url을 찾을 수 있음
    path('qr/', qregiste, name='qr'),
    path('cr/', cregiste, name='cr'),
    path('<int:q_id>/qchange/', qupdate, name='qu'),
    path('<int:q_id>/qdelete/', qdelete, name='qd'),
    path('<int:c_id>/cdelete/', cdelete, name='cd'),
    path('<int:c_id>/cchange/', cupdate, name='cu')
    ]

django4/src/vote/models.py
from django.db import models

# Create your models here.
#question 모델 클래스
#설문 제목,설문 생성일
class Question(models.Model):
    name = models.CharField(max_length = 200)
    #DateField는 날짜 데이터를 저장할 수 있는 저장공간
    #DatetimeField는 날짜 + 시간 데이터를 저장 할 수 있는 공간
    pub_date = models.DateField()
    
    def __str__(self):
        return self.name
#choice 모델 클레스
#답변 항목 내용,투표 수 ,어떤 question과 연결 되있는지?(외래키)
class Choice(models.Model):
    name =models.CharField(max_length = 50)
    #IntegerField: 정수값 데이터를 저장 할 수 있는 공간
    #default: 모든 field 클래스에 존재하는 매개변수로,객체 생성시 기본값설정을 할수있음
    votes= models.IntegerField(default=0)
    #Question 모델클래스와 1:n관계를 가지는 설정.
    #Choice 객체가 연결한 Question객체가 삭제가 되면,자신도 삭제되도록 설정
    #ex)글 삭제하면 그 글에 작성된 댓글이 같이 삭제됨
    q = models.ForeignKey(Question,on_delete=models.CASCADE)
    
    #self.q.name: 현재 choice객체가 연결한 Question 객체의 이름 불러옴
    def __str__(self):
        return self.q.name + '/' + self.name
'''
models.Foreignkey:다른 모델클래스의 객체와 해당 모델 클래스의 객체가 연결관계를 가지는 저장 공간
Foreignkey(연결할 모델,on_delete= 연결객체 삭제시 ,삭제 방식)
현재 chioce 모델 클래스의 q변수는 연결한 QUestion객체를 의미함
>choice 객체.q.name: 연결된 모델클래스의 객체가 삭제될떄 연결한 객체들을 어떻게 처리할지
지정하는 변수
models.CASCADE:연결된 모델클래스의 객체가 삭제될떄 같이 삭제
models.PROTECT:연결된 모델클래스가 삭제되지 않도록 막아줌
models.SET_NULL:연결된 객체가 삭제되면 아무것도 연결하지 않은 상태 유지
models.SET(연결할객체):연결된 객체가 삭제되면 매개변수로 넣은 객체와 연결
models.SET_DEFAULT: 연결된 객체가 삭제되면 기본값 객체와 연결
'''

django4/src/vote/forms.py
'''
Form : django에서 html코드에 들어갈 <input>태그를 파이썬 코드 형태로 관리할 수 있도록 제공하는 기능

Form은 모델클래스를 기반으로 입력공간을 생성할 수도 있고, 커스텀 입력양식을 생성할 수도 있음.
ModelForm : 모델클래스와 연동된 폼을 만들때 상속받는 클래스
Form : 커스텀 입력양식으로만 폼을 만들떄 상속받는 클래스

장점
Model클래스에 변동사항을 자동으로 Form클래스가 인지해서 사용자가 입력할
수있는 공간을 변경해줌. 디자이너가 직접 입력양식을 만들지 않아도 됨
'''


from django.forms.models import ModelForm
from vote.models import Question,Choice

#Question 모델클래스와 연동된 모델폼클래스 정의
#클라이언트가 Question 객체를 추가/수정 할때 사용
class QuestionForm(ModelForm):
    #Meta 클래스 : 연동하고자하는 모델클래스에 대한 정보를 정의하는 클래스
    class Meta:
        #model,fields,exclude,widgets
        #model : 연동할 모델클래스 이름을 저장하는 변수
        model = Question
        #fields : 사용자가 입력할 수 있는 <input>태그를 생성할 때,
        #모델클래스에 정의된 변수들 중 어떤 변수를 클라이언트에게 제공할것인지 지정
        #exclude : 모델클래스에 정의된 변수 중 어떤 변수를 제외하고 클라이언트에게 제공 할 것인지 지정
        #변수이름은 문자열 형태로, 저장하는 타입은 리스트형태로
        #fields나 exclude 변수 중 한개만 사용
        fields = ['name']
        #exclude = ['pub_date']
        
        
#Choice 모델클래스와 연동된 모델폼크랠스 정의
#클라이언트가 choice 객채를 추가/수정 할때 사용
class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['q','name']
        #exclude = ['votes']
        

django4/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from vote.models import Question, Choice
from django.contrib.auth.decorators import login_required
"""
데코레이터: 뷰함수가 실행되기전에 먼저 실행되는 함수
login_required : 뷰함수가 실행되기전 웹클라이언트의 로그인 여부를 파악하고
비로그인 상태인 웹글라이언트에게 로그인페이지를 리다이렉트 해주는 데코레이터

데코레이터를 뷰함수에 적용하는 방법
#@ 적용할 데코레이터 함수 이름
def 뷰함수()
"""
# Create your views here.
# 설문조사 리스트가 뜨는 메인페이지
def index(request):
    #데이터베이스에 저장된 Question 객체 리스트로 추출
    a = Question.objects.all()
    #index.html 전달
    return render(request, 'vote/index.html',{'a':a})
#설문조사 페이지
def detail(request,q_id):
    #question 객체들 중 q_id와 동일한 값을 id변수에 가진 객체 추출
    #또는 조건에 맞는 객체가 없으면 404번에러를 클라이언트에 전달
    q = get_object_or_404(Question, id = q_id )
    '''
    get_object_or_404(모델클래스,조건):모댈클래스에 조건을 검색해 1개의 객체 호출
    만약 객체가 없는 경우, 클라이언트의 잘못된 접근으로 판단해 뷰함수를 종료하고 404에러 전달
    
    현재 Qusetion 모댈클래스는 choice 모델클래스가 외래키로 연결한 상태이므로,
    question 객체들은 자신과 연결된 choice 객체들을 추출 할 수있음
    question 객체.choice_set.all(또는 get,filter,exclude)로 데이터베이스에 저장된
    choice 객체 추출 가능 . 모델클래스 이름을 소문자로 작성해야함
    '''
    #question 객체로 연결된 choice 객체들을 모두 추출
    c_list = q.choice_set.all()
    
    #HTML 파일 전달
    return render(request,'vote/detail.html',{'q':q,'c_list':c_list})

from django.http.response import HttpResponseRedirect, HttpResponseRedirectBase
'''
HttpResponseRedirect(url 주소)
: 웹클라이언트가 html파일을 받는것이 아닌, 새로운 url주소를 받아 재요청을
할 수 있도록 처리할 수 있는 클래스.
사용방법
return HttpResponseRedirect(이동할 url 주소)

Redirect : 웹서버가 300번대 코드를 전달하면서 더 처리해야할 요청을
웹 클라이언트에게 전달하는 응답

'''
#투표 반영
def vote(request):
    #사용자의 요청이 POST방식인지 확인
    #request.method:웹클라이언트의 요청방식을 저장한 변수
    if request.method == "POST":
        '''
        request.POST또는 request.GET:웹클라이언트의 요청과 함께 날라온 데이터를 저장한 변수
        값을 꺼낼때, HTML코드에 name 속성 이름으로 값을 추출할 수 있다
        '''
        print(request.POST)
        #사용자가 투표한 choice객체의 id값을 추출
        c_id = request.POST.get('vote')
        #id값을 바탕으로 데이터베이스에 choice객체 추출
        c = get_object_or_404(Choice, id=c_id)
        
        #votes 변수에 투표반영
        c.votes = c.votes + 1
        
        #데이터베이스에 변경사항 저장
        c.save()
        #다른 뷰함수의 URL을 웹클라이언트에게 전달
        #c.q:choice 객체가 연결한 question 객체 변수
        #c.q.id: 연결한 question 객체의 id변수값
        url = '/vote/result/%s/' % c.q.id
        return HttpResponseRedirect(url)
#결과 페이지
def result(request, q_id):
    #Question객체를 q_id값으로 한개 추출
    q = get_object_or_404(Question,id = q_id)
    #HTML 전달
    return render(request, 'vote/result.html',{'q':q})
#모델폼클래스 임포트
from vote.forms import QuestionForm, ChoiceForm
from _datetime import datetime#컴퓨터의 현재 날짜/시간을 대입
#데이터베이스에 새로만든 모델겍체 저장
#모델객체.save() : 새로운 객체를 저장하거나 기존 객체의 변수값변경을 데이터베이스에 저장할 수있다
#Question 객체 추가
@login_required
def qregiste(request):
    #웹클라이언트의 요청방식 구분
    #-> 하나의 뷰에 두가지 기능을 구현하고자함
    #get 방식요청
    if request.method == "GET":
        #폼클래스 객체를 생성 및 HTML파일 전달
        #폼클래스 객체 생성 시 , 매개변수를 입력하지 않으면,
        #<input>태그에 아무런 값도 채워져있지 않은 상태로 생성됨
        obj = QuestionForm()
        '''
        form 객체를 기반으로 html 코드에 들어갈 <input>태그를 생성할 때, as_p(),as_table(),as_ul()함수를 사용 할 수있음,
        as_p():설명과 입력공간이 <P>태그로 묶여잇는 html코드로 변환
        as_table:설명과 입력공간이 한행<tr>에 묶여있는 html코드로 변환
        as_ul:설명과 입력공간이 리스트아이템에 묶여있는 html코드로 변환
        '''
        print('as_table() 결과' , obj.as_table())
        return render(request, 'vote/qregiste.html',{'form': obj.as_table()})
    #post 방식요청
        #사용자 입력 기반으로 폼클래스객체를 생성
    elif request.method == "POST":#POST요청 시 동봉된 사용자의 입력데이터
        obj = QuestionForm(request.POST)
        #폼클래스 객체를 연동된 모델클래스 객체를 변환
        #q : 사용자 입력으로 name변수에 값이 채워져있는 Question객체
        #폼객체.save() : 데이터베이스에 사용자 입력 기반의 새로운 객체가
        #저장되면서 새로운 객체를 반환하는 함수
        #사용자는 pub_date변수에 값을 입력할 수없기 때문에, 폼객체를 바로
        #데이터베이스에 저장 할수 없음(pub_date변수의 값이 없는 상태)
        #따라서 question객체로 변환 한뒤 , 비어있는 변수를 채워줘야함
        #>폼객체.save(commit=False)
        q = obj.save(commit=False)
        print('저장 전 id변수 값:',q.id)#데이터베이스에 저장되지않은 변수의 id값은 None이 뜸
        #값이 채워져있지않은 변수에 값을 채움
        q.pub_date = datetime.now()
        #데이터베이스에 새로만든 모델객체 저장
        q.save()
        print('저장이 된 다음의 id변수값:',q.id)
        #다른 url로 이동
        return HttpResponseRedirect('/vote/%s/'%q.id)
#Question 객체 수정
@login_required
def qupdate(request,q_id):
    pass
    #수정할 대상의 객체 추출
    q = get_object_or_404(Question,id = q_id)
    #GET 방식 요청
    if request.method == 'GET':
        #수정할 객체를 기반으로 QuestionForm 객체를 생성
        obj = QuestionForm(instance=q)    
        #HTML 파일 전달
        return render(request,'vote/qupdate.html',{'form':obj.as_p()})
    #POST 방식 요청
    elif request.method == "POST":
        #사용자입력+수정할객체를 기반으로 QuestionForm 객체를 생성
        obj = QuestionForm(request.POST,instance=q)
        #수정을 하는 객체를 바탕으로 QuestionForm 객체가 생성됬기떄문에
    #>바로 데이터베이스에 저장
    w = obj.save()
    print('수정할 객체 q의 id:',q_id)
    print('폼객체가 준 객체의 id:',w.id)
    #다른 url 전달
    return HttpResponseRedirect('/vote/%s/'% w.id)
    
#Question 객체 삭제
@login_required
def qdelete(request,q_id):
    q = get_object_or_404(Question,id=q_id)
    q.delete() #데이터베이스에서 삭제됨
    print('삭제후id:',q.id)
    return render(request,'vote/qdelete.html',{'title':q.name,'type':1})
#Choice 객체 추가
@login_required
def cregiste(request):
    #GET 요청
    if request.method == "GET":
    #ChoiceForm 객체 생성 및 HTML('vote.cregiste.html') 전달
        obj = ChoiceForm()
        return render(request, 'vote/cregiste.html',{'form': obj.as_table()})
    #POST 요청
    elif request.method == "POST":
        #사용자입력기반으로 ChoiceForm 객체 생성
        obj = ChoiceForm(request.POST)
        #ChoiceForm객체를 기반으로 Choice객체 생성 및 데이터베이스 저장
        c = obj.save()
        #->값이 비어있는 변수가 없기때문(votes는 기본값 설정이 되있음)
        #다른 페이지로 이동(index나 detail로 이동)
        #return HttpResponseRedirect('/vote/')#index페이지 url
        return HttpResponseRedirect('/vote/%s/'% c.q.id)#연동된 Question객체의 detail페이지의 url
#Choice 객체 수정
@login_required
def cupdate(request,c_id):
    c = get_object_or_404(Choice,id = c_id)
    if request.method == "GET":
        obj = ChoiceForm(instance = c)
        return render(request,'vote/cupdate.html',{'obj':obj})
    elif request.method == "POST":
        obj = ChoiceForm(request.POST, instance=c)
        obj.save()
        #detail View의 url을 전달
        return HttpResponseRedirect('/vote/%s/' % c.q.id)
#Choice 객체 삭제
@login_required
def cdelete(request,c_id):
    #choice객체 찾기
    c = get_object_or_404(Choice,id=c_id)
    #데이터베이스에서 삭제
    c.delete()
    return render(request,'vote/cdelete.html',{'title':c.name,'type':2})
    #HRML 파일 or URL주소 전달
    #urls.py에 함수 등록

django4/src/vote/templates/vote/cdelete.html
{% extends 'base.html' %}
{% block content %}
{#title : 삭제된 객체의 항목이름, type:1=Question,2=Choice 삭제됨#}
<p>
{% if type == 1%}
{% else %}
{% endif %}
{{title}}이 성공적으로 삭제되었습니다.
</p>
<a href="/vote/">메인으로 돌아가기</a>

{% endblock %}

django4/src/vote/templates/vote/cregiste.html
{% extends 'base.html' %}
{% block content %}
{#form:html <input>태그가 있는 테이블형식 문자열#}
<h3>답변항목 추가</h3>

<form action="/vote/cr/" method="POST">
	{% csrf_token %}
	<table border=1>
	{{ form }}
	</table>
	<input type='submit' value="추가"> 
</form>
{%endblock%}

django4/src/vote/templates/vote/cupdate.html
{% extends 'base.html' %}
{% block content %}
<h3>답변 항목 수정</h3>
{# obj : ChoiceForm 객체#}
<form action="" method="POST">
	{% csrf_token %}
	<ul>
		{{obj.as_ul }}
	</ul>
	<input type="submit" value="수정">
</form>


<a href="/vote/">메인페이지로 돌아가기</a>

{%endblock%}

django4/src/vote/templates/vote/detail.html
{% extends 'base.html' %}
{% block content %}
{# q : Question 객체, c_list : Choice 객체 리스트 #}

<h3>{{q.name}}</h3>
<form action='/vote/vote/' method='post'>
	{% csrf_token %}
	{% for c in c_list %}
		<input type="radio" name="vote" value = "{{c.id}}">
		<label>{{ c.name }}</label>
		<a href="{%url 'vote:cu' c.id%}">수정</a>
		<a href="{%url 'vote:cd' c.id%}">삭제</a>
		<br>
	{%endfor%}
	<input type="submit" value = "투표">	
</form>	
<a href="{%url 'vote:cr' %}">답변항목 추가하기</a>
{%endblock%}

django4/src/vote/templates/vote/index.html
{% extends 'base.html' %}
{% block content %}
{# a: Question 객체 리스트 #}
<h3>설문조사 메인페이지</h3>
<ul>
	{% for b in a %}
		<li> <a href="/vote/{{b.id}}">{{b.name}}</a> 생성일 : {{b.pub_date}} 
		<a href="{%url 'vote:qu' b.id%}">수정</a>
		<a href="{%url 'vote:qd' b.id%}">삭제</a>
		</li>
	{% endfor %}
</ul>
<a href="{%url 'vote:qr' %}">설문조사 추가하기</a>
{%endblock%}

django4/src/vote/templates/vote/qdelete.html
{% extends 'base.html' %}
{% block content %}
{#title : 삭제된 객체의 항목이름, type:1=Question,2=Choice 삭제됨#}
<p>
{% if type == 1%}
{% else %}
{% endif %}
{{title}}이 성공적으로 삭제되었습니다.
</p>
<a href="/vote/">메인으로 돌아가기</a>
{% endblock %}

django4/src/vote/templates/vote/qregiste.html
{% extends 'base.html' %}
{% block content %}
<h3>질문 생성</h3>

<form action="" method="POST">
 {% csrf_token %}
 <table>
 	{{form}}
 </table>
 <input type='submit' value="생성">
</form>

<a href="/vote/">메인으로 돌아가기</a>
{% endblock %}

django4/src/vote/templates/vote/qupdate.html
{% extends 'base.html' %}
{% block content %}
<h3>설문조사 수정하기</h3>
{# form : <input>이 구성된 <p>형식의 HTML코드 문자열#}
<form action="" method="post">
	{% csrf_token%}
	{{ form }}
	<input type = "submit" value="수정">
</form>
<a href="/vote/">메인으로 돌아가기</a>

{%endblock%}

django4/src/vote/templates/vote/result.html
{% extends 'base.html' %}
{% block content %}
{#q: Question 객체#}
<h3>{{q.name}}의 투표 결과</h3>

<ol>
	{# HTML 코드에서 함수를 사용할 수 있으나, 매개변수를 입력할수없도록 소괄호 생략 #}
	{% for c in q.choice_set.all %}
		<li>{{c.name}} - {{c.votes}} 표</li>
		
	{% endfor %}
</ol>
<a href="/vote/">메인으로 돌아가기</a>
{% endblock %}